### ISSUE TITLE
Update firestore filtering

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#431]
Our tests have started producing a deprecation warning from the Firestore API:
```
kcidb/test_monitor.py::test_email_generated[empty_deployment]
  /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/google/cloud/firestore_v1/base_collection.py:290: UserWarning: Detected filter using positional arguments. Prefer using the 'filter' keyword argument instead.
    return query.where(field_path, op_string, value)
```

Update the interface we're using so the warning disappears.

**Comment by mharyam** [comment]
Hello @spbnick, can I work on this?

**Comment by spbnick** [comment]
Heeey, Maryam! Long time no see :grinning: Sure, feel free to pick this up!

**Comment by mharyam** [comment]
> Heeey, Maryam! Long time no see 😀 Sure, feel free to pick this up!

It's been a while 😄, will send a PR soon

**Comment by mharyam** [comment]
@spbnick
Sorry, I am just getting back. I have been dealing with setting up the project.

I realized I am not getting the same depreciation message as the one above. I am using Python 3.11.6. Does the Python version matter?

Or should I focus on fixing the depreciation error I am getting for mine, since I couldn't reproduce yours?

This is what mine is showing 
<img width="1434" alt="Screenshot 2023-10-10 at 12 19 44 AM" src="https://github.com/kernelci/kcidb/assets/21172249/308215ff-ca34-4497-a76b-ee037fc32a1a">

**Comment by spbnick** [comment]
@mharyam, no, we cannot do anything regarding the deprecation warnings you see, this is for Google to fix, I think.

You need a deployment to reproduce this. You could create a Google Cloud project, do a test deployment there, and run the test to see this. I can give you the commands to do this, if you'd like to do that.

However, here's an example of this appearing in the wild: https://github.com/kernelci/kcidb/actions/runs/6695988962/job/18193278781#step:8:257
