### ISSUE TITLE
Consider supporting upgrading to a specific version with kcidb-upgrade

### ISSUE THREAD

**Issue by spbnick** [kernelci/kcidb#79]
The `kcidb-upgrade` tool can be used for upgrading the I/O data schema. However, it only supports upgrading from any known version to the latest version. Sometimes, though, it could be useful to upgrade to an older version. E.g. to see what an older version of KCIDB would do, or to debug an upgrading issue.

Consider adding support for a command-line option accepting the major version number of a target schema to kcidb-upgrade. The option should default to the latest version, if unspecified.

**Comment by spbnick** [comment]
This could help with debugging upgrades.

**Comment by spbnick** [comment]
Or, perhaps, make the target version an optional positional argument.

**Comment by pgadige** [comment]
I have a query, @spbnick Could you please help me understand this specific use case.

When I ran `kcidb-upgrade` tool with no arguments, I saw a blinking cursor on a new line. The cursor continued to blink for several minutes ( > 30 minutes). I explicitly exited using KeyBoardInterrupt Ctrl + C. I wonder if this is an expected behaviour of `kcidb-upgrade` tool. Intuitively, I expected an output indicating either successful upgrade of I/O JSON data to the latest version or inform the current I/O JSON data is already the latest version. Since running `kcidb-upgrade` with no arguments doesn't complain, I assume that the usage of command is correct. Am I missing something? 

An [image](https://pasteboard.co/rfsN27vQurqT.png) of what I see on my screen.
